language: cpp
dist: trusty
sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - [ g++-7, libboost-all-dev ]

script:
    - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake .
    - cmake --build . -- -j2
